[package]
name = "pip-udeps"
version = "0.1.0"
authors = ["Lev Ostatnigrosh <levostatnigrosh@pm.me>"]
description = "Find unused dependencies in a Python project"
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.4.18", features = ["derive"] }
rustpython-parser = "0.3.0"
tempfile = "3.10.1"
walkdir = "2.5.0"
