[package]
authors = ["Lev Ostatnigrosh <levostatnigrosh@pm.me>"]
categories = ["command-line-utilities"]
about = "A tool to find unused imports in Python code."
name = "pip-udeps"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.4.18", features = ["derive"] }
rustpython-parser = "0.3.0"
walkdir = "2.5.0"
